-- =====================================================================
-- 043_044_VIP_STAGING_APPLY.sql
-- VIP onboarding — Phase 1 (track generalisation) + Phase 2 (AIR).
--
-- Paste this whole file into the Supabase Studio SQL editor for the
-- STAGING project (exqmxvdtcsvpgtftwjml) and run it once.
--
-- Generated by concatenating, verbatim and in order:
--   backend/migrations/043_vip_track_generalisation.sql
--   backend/migrations/044_vip_air.sql
--
-- Both are additive, idempotent and independently transactional, so:
--   * running this twice is harmless
--   * if 044 fails, 043 stays committed and can be re-run safely
--   * applying it BEFORE the backend deploy is the safe direction
--     (043's new `track` column defaults to 'tir', so the currently
--     deployed TIR code keeps working untouched)
--
-- Deploying the backend BEFORE this runs takes the founder portal down:
-- the code hard-references `track` and the vip_air_* tables.
--
-- Verification queries are at the bottom, commented out. Run them
-- separately AFTER this succeeds.
-- =====================================================================

-- ─────────────────────────────────────────────────────────────────────
-- 043_vip_track_generalisation.sql
-- ─────────────────────────────────────────────────────────────────────

-- 043_vip_track_generalisation.sql — let VIP (track 'sip') founders use the
-- shared half of the Founder Portal.
--
-- Only five founder_* tables are genuinely shared between the two tracks:
-- the MOU and the four Founders-Resources tables. The eight TIR-only cohort
-- tables (experiments, tasks, review, team_members, approach, bom_items,
-- equipment_items, procurement_items) are deliberately NOT touched — VIP has
-- its own cohort-management sections and never reads them.
--
-- The FK to tir_applications(id) has to go: Postgres has no polymorphic
-- foreign key, and application_id may now point at either tir_applications or
-- sip_applications. The exposure is contained — RLS denies every non
-- service-role writer, the /founder router is the only writer and it enforces
-- ownership, and applications are never hard-deleted in this system.
--
-- Additive and re-runnable. Existing rows take the 'tir' default.

begin;

-- 1) founder_mou ----------------------------------------------------------
alter table public.founder_mou
  add column if not exists track text not null default 'tir';
alter table public.founder_mou
  drop constraint if exists founder_mou_track_check;
alter table public.founder_mou
  add constraint founder_mou_track_check check (track in ('tir','sip'));
alter table public.founder_mou
  drop constraint if exists founder_mou_application_id_fkey;
-- one MOU per application PER TRACK (was: one per application_id globally)
alter table public.founder_mou
  drop constraint if exists founder_mou_application_id_key;
create unique index if not exists founder_mou_track_application_uidx
  on public.founder_mou (track, application_id);

-- 2) founder_cart_items ---------------------------------------------------
alter table public.founder_cart_items
  add column if not exists track text not null default 'tir';
alter table public.founder_cart_items
  drop constraint if exists founder_cart_items_track_check;
alter table public.founder_cart_items
  add constraint founder_cart_items_track_check check (track in ('tir','sip'));
alter table public.founder_cart_items
  drop constraint if exists founder_cart_items_application_id_fkey;
create index if not exists idx_founder_cart_track_app
  on public.founder_cart_items (track, application_id);

-- 3) founder_resource_requests --------------------------------------------
alter table public.founder_resource_requests
  add column if not exists track text not null default 'tir';
alter table public.founder_resource_requests
  drop constraint if exists founder_resource_requests_track_check;
alter table public.founder_resource_requests
  add constraint founder_resource_requests_track_check check (track in ('tir','sip'));
alter table public.founder_resource_requests
  drop constraint if exists founder_resource_requests_application_id_fkey;
create index if not exists idx_founder_requests_track_app
  on public.founder_resource_requests (track, application_id);

-- 4) founder_bookings -----------------------------------------------------
alter table public.founder_bookings
  add column if not exists track text not null default 'tir';
alter table public.founder_bookings
  drop constraint if exists founder_bookings_track_check;
alter table public.founder_bookings
  add constraint founder_bookings_track_check check (track in ('tir','sip'));
alter table public.founder_bookings
  drop constraint if exists founder_bookings_application_id_fkey;
create index if not exists idx_founder_bookings_track_app
  on public.founder_bookings (track, application_id);

-- 5) founder_tickets ------------------------------------------------------
alter table public.founder_tickets
  add column if not exists track text not null default 'tir';
alter table public.founder_tickets
  drop constraint if exists founder_tickets_track_check;
alter table public.founder_tickets
  add constraint founder_tickets_track_check check (track in ('tir','sip'));
alter table public.founder_tickets
  drop constraint if exists founder_tickets_application_id_fkey;
create index if not exists idx_founder_tickets_track_app
  on public.founder_tickets (track, application_id);

commit;

-- ─────────────────────────────────────────────────────────────────────
-- 044_vip_air.sql
-- ─────────────────────────────────────────────────────────────────────

-- 044_vip_air.sql — ARTPARK Innovation Readiness (AIR) assessment, VIP only.
--
-- Unlike the five shared tables in 043, these are VIP-only, so they keep real
-- foreign keys to sip_applications(id). No `track` column: there is nothing to
-- disambiguate.
--
-- RLS enabled with NO policies: every access is backend-mediated via the
-- service-role client, and the /founder/air router enforces that the
-- application belongs to the caller — same pattern as 040-043.

begin;

-- 1) One assessment round per venture per quarter.
create table if not exists public.vip_air_assessments (
  id                uuid primary key default gen_random_uuid(),
  application_id    uuid not null references public.sip_applications(id) on delete cascade,
  round_label       text not null,
  status            text not null default 'draft'
                      check (status in ('draft','submitted','verified')),
  submitted_at      timestamptz,
  verified_at       timestamptz,
  verified_by       uuid,
  overall_claimed   int check (overall_claimed between 1 and 9),
  overall_verified  int check (overall_verified between 1 and 9),
  tech_claimed      int check (tech_claimed between 1 and 9),
  tech_verified     int check (tech_verified between 1 and 9),
  comm_claimed      int check (comm_claimed between 1 and 9),
  comm_verified     int check (comm_verified between 1 and 9),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (application_id, round_label)
);
alter table public.vip_air_assessments enable row level security;
create index if not exists idx_vip_air_assessments_app
  on public.vip_air_assessments(application_id);

-- 2) Six lever scores per round — claimed by the founder, verified by ARTPARK.
create table if not exists public.vip_air_lever_scores (
  id                uuid primary key default gen_random_uuid(),
  assessment_id     uuid not null references public.vip_air_assessments(id) on delete cascade,
  lever             text not null check (lever in (
                      'scientific_principles','architecture','qualification',
                      'user_needs','supply_chain','reliability')),
  q1_option         text,
  q2_option         text,
  q3_option         text,
  criteria_checked  jsonb not null default '[]'::jsonb,
  claimed_level     int check (claimed_level between 1 and 9),
  verified_level    int check (verified_level between 1 and 9),
  verifier_note     text,
  verified_at       timestamptz,
  verified_by       uuid,
  updated_at        timestamptz not null default now(),
  unique (assessment_id, lever)
);
alter table public.vip_air_lever_scores enable row level security;
create index if not exists idx_vip_air_scores_assessment
  on public.vip_air_lever_scores(assessment_id);

-- 3) Qualifying documents uploaded per lever per claimed level.
create table if not exists public.vip_air_evidence (
  id                uuid primary key default gen_random_uuid(),
  assessment_id     uuid not null references public.vip_air_assessments(id) on delete cascade,
  lever             text not null check (lever in (
                      'scientific_principles','architecture','qualification',
                      'user_needs','supply_chain','reliability')),
  air_level         int not null check (air_level between 1 and 9),
  doc_label         text not null,
  storage_path      text not null,
  -- not null: the (assessment_id, lever, air_level, filename) unique
  -- constraint below is the only thing standing between a re-upload and a
  -- duplicate row, and Postgres treats every NULL as distinct from every
  -- other NULL — a NULL filename would let the constraint be defeated
  -- silently, one row per re-upload, forever.
  filename          text not null,
  size_bytes        int,
  content_type      text,
  uploaded_at       timestamptz not null default now(),
  -- Keyed on filename too, not just (assessment_id, lever, air_level):
  -- uploading two differently-named supporting documents for one claimed
  -- level is legitimate (assessment_bundle exposes evidence as a list per
  -- lever) — only re-uploading the exact same slot should collide.
  unique (assessment_id, lever, air_level, filename)
);
alter table public.vip_air_evidence enable row level security;
create index if not exists idx_vip_air_evidence_assessment
  on public.vip_air_evidence(assessment_id);

-- 4) Private bucket for AIR evidence documents. Service-role only; the
-- backend issues short-lived signed URLs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('vip-founder-docs','vip-founder-docs', false, 26214400,
        array['application/pdf','image/png','image/jpeg',
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
              'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
on conflict (id) do nothing;

commit;

-- =====================================================================
-- VERIFICATION — run these SEPARATELY, after the above succeeds.
-- Uncomment one at a time. Each is a single flat statement on purpose:
-- the Studio editor can execute a mid-statement fragment, which turns a
-- multi-line `exists (...)` into a 42601 syntax error that looks like a
-- failed migration. None of these use LIKE with an underscore escape,
-- for the same class of reason.
-- =====================================================================

-- 1) The five shared tables each gained `track`. Expect 5 rows,
--    column_default = 'tir'::text, is_nullable = NO.
-- select table_name, column_default, is_nullable from information_schema.columns where table_schema = 'public' and column_name = 'track' and table_name in ('founder_mou','founder_cart_items','founder_resource_requests','founder_bookings','founder_tickets') order by table_name;

-- 2) Their foreign keys to tir_applications are gone. Expect 0 rows.
-- select conrelid::regclass::text as tbl, conname from pg_constraint where contype = 'f' and conrelid::regclass::text in ('founder_mou','founder_cart_items','founder_resource_requests','founder_bookings','founder_tickets');

-- 3) founder_mou uniqueness moved to (track, application_id).
--    Expect founder_mou_track_application_uidx in the list.
-- select indexname from pg_indexes where schemaname = 'public' and tablename = 'founder_mou' order by indexname;

-- 4) The three AIR tables exist. Expect 3 rows.
-- select table_name from information_schema.tables where table_schema = 'public' and table_name in ('vip_air_assessments','vip_air_lever_scores','vip_air_evidence') order by table_name;

-- 5) The evidence bucket exists and is PRIVATE. Expect one row, public = false.
-- select id, public, file_size_limit from storage.buckets where id = 'vip-founder-docs';

-- 6) RLS is on for all three AIR tables with no policies.
--    Expect 3 rows, relrowsecurity = true.
-- select relname, relrowsecurity from pg_class where relname in ('vip_air_assessments','vip_air_lever_scores','vip_air_evidence') order by relname;

-- 7) No policies on them. Expect 0 rows.
-- select tablename, policyname from pg_policies where schemaname = 'public' and tablename in ('vip_air_assessments','vip_air_lever_scores','vip_air_evidence');
