"""Editable DOCX and readable PDF renderers for structured VIP pilot memos."""
from __future__ import annotations

import io
from typing import Any

from docx import Document
from docx.shared import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _label(key: str) -> str:
    return key.replace("_", " ").title()


def _lines(value: Any, prefix: str = "") -> list[str]:
    if value is None:
        return []
    if isinstance(value, (str, int, float, bool)):
        return [f"{prefix}{value}"]
    if isinstance(value, list):
        out: list[str] = []
        for item in value:
            out.extend(_lines(item, prefix="• "))
        return out
    if isinstance(value, dict):
        out = []
        for key, item in value.items():
            if isinstance(item, (str, int, float, bool)):
                out.append(f"{prefix}{_label(key)}: {item}")
            else:
                out.append(f"{prefix}{_label(key)}:")
                out.extend(_lines(item, prefix="  "))
        return out
    return [f"{prefix}{value}"]


def render_docx(memo: dict[str, Any]) -> bytes:
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)
    style = document.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(10)
    document.add_heading("CONFIDENTIAL — INVESTMENT COMMITTEE MEMO", 1)
    for key, value in memo.items():
        if key in {"meta", "memo_scores"}:
            continue
        document.add_heading(_label(key), 2)
        for line in _lines(value):
            document.add_paragraph(line, style="List Bullet" if line.startswith("•") else None)
    if memo.get("memo_scores") is not None:
        document.add_heading("Memo scores", 2)
        for line in _lines(memo["memo_scores"]):
            document.add_paragraph(line)
    if memo.get("meta"):
        document.add_paragraph(f"Generated by {memo['meta'].get('model', '[To be confirmed]')} · pilot")
    output = io.BytesIO()
    document.save(output)
    return output.getvalue()


def render_pdf(memo: dict[str, Any]) -> bytes:
    output = io.BytesIO()
    doc = SimpleDocTemplate(output, pagesize=letter, rightMargin=.8 * inch,
                            leftMargin=.8 * inch, topMargin=.8 * inch, bottomMargin=.8 * inch)
    styles = getSampleStyleSheet()
    body = ParagraphStyle("MemoBody", parent=styles["BodyText"], fontName="Helvetica",
                          fontSize=9.5, leading=13, alignment=TA_LEFT, spaceAfter=4)
    heading = ParagraphStyle("MemoHeading", parent=styles["Heading2"], fontName="Helvetica-Bold",
                             fontSize=13, leading=16, textColor=colors.HexColor("#182a54"), spaceBefore=10)
    story = [Paragraph("CONFIDENTIAL — INVESTMENT COMMITTEE MEMO", heading)]
    for key, value in memo.items():
        if key in {"meta", "memo_scores"}:
            continue
        story.append(Paragraph(_label(key), heading))
        for line in _lines(value):
            story.append(Paragraph(line.replace("&", "&amp;"), body))
    if memo.get("memo_scores") is not None:
        story.append(Paragraph("Memo scores", heading))
        rows = [[_label(k), str(v.get("score", v) if isinstance(v, dict) else v)]
                for k, v in memo["memo_scores"].items()]
        table = Table(rows, colWidths=[3.8 * inch, 1 * inch])
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9eef8")),
                                   ("GRID", (0, 0), (-1, -1), .25, colors.HexColor("#b9c2d0")),
                                   ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                                   ("FONTSIZE", (0, 0), (-1, -1), 9)]))
        story.append(table)
    doc.build(story)
    return output.getvalue()
