"""Editable DOCX and readable PDF renderers for structured VIP pilot memos."""
from __future__ import annotations

import io
from typing import Any

from docx import Document
from docx.shared import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


MEMO_ORDER = (
    "title_block", "deal_snapshot", "company_explanation", "why_solution_matters",
    "product_business_model", "technology_edge", "competitive_landscape",
    "addressable_market", "founding_team", "milestones", "use_of_funds",
    "risks_mitigants", "ic_recommendation", "ic_reviewer_notes", "attribution",
)

def _label(key: str) -> str:
    return key.replace("_", " ").title()


def _lines(value: Any, prefix: str = "") -> list[str]:
    if value is None:
        return []
    if isinstance(value, (str, int, float, bool)):
        return [f"{prefix}{value}"]
    if isinstance(value, list):
        out: list[str] = []
        for item in value:
            out.extend(_lines(item, prefix="• "))
        return out
    if isinstance(value, dict):
        out = []
        for key, item in value.items():
            if isinstance(item, (str, int, float, bool)):
                out.append(f"{prefix}{_label(key)}: {item}")
            else:
                out.append(f"{prefix}{_label(key)}:")
                out.extend(_lines(item, prefix="  "))
        return out
    return [f"{prefix}{value}"]


def render_docx(memo: dict[str, Any]) -> bytes:
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)
    style = document.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(10)
    document.add_heading("CONFIDENTIAL — INVESTMENT COMMITTEE MEMO", 1)
    for key, value in memo.items():
        if key in {"meta", "memo_scores"}:
            continue
        document.add_heading(_label(key), 2)
        for line in _lines(value):
            document.add_paragraph(line, style="List Bullet" if line.startswith("•") else None)
    if memo.get("memo_scores") is not None:
        document.add_heading("Memo scores", 2)
        for line in _lines(memo["memo_scores"]):
            document.add_paragraph(line)
    if memo.get("meta"):
        document.add_paragraph(f"Generated by {memo['meta'].get('model', '[To be confirmed]')} · pilot")
    output = io.BytesIO()
    document.save(output)
    return output.getvalue()


def render_pdf(memo: dict[str, Any]) -> bytes:
    """Render a flat, sharp-cornered ARTPARK investment memo PDF."""
    from xml.sax.saxutils import escape

    output = io.BytesIO()
    doc = SimpleDocTemplate(
        output,
        pagesize=letter,
        rightMargin=0.72 * inch,
        leftMargin=0.72 * inch,
        topMargin=0.68 * inch,
        bottomMargin=0.68 * inch,
    )
    styles = getSampleStyleSheet()
    ink = colors.HexColor("#242424")
    ink_soft = colors.HexColor("#4a4a52")
    ink_dim = colors.HexColor("#8a8a92")
    line = colors.HexColor("#e3e3e8")
    purple = colors.HexColor("#3213b7")
    paper_soft = colors.HexColor("#f6f6f8")
    kicker = ParagraphStyle(
        "MemoKicker", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=10, leading=13, textColor=purple, spaceAfter=8,
    )
    title = ParagraphStyle(
        "MemoTitle", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=27, leading=31, textColor=ink, spaceAfter=15,
    )
    heading = ParagraphStyle(
        "MemoHeading", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=13, leading=17, textColor=ink, spaceBefore=15,
        spaceAfter=6, keepWithNext=True,
    )
    body = ParagraphStyle(
        "MemoBody", parent=styles["BodyText"], fontName="Helvetica",
        fontSize=9.5, leading=13.5, textColor=ink_soft, spaceAfter=5,
    )
    score_label = ParagraphStyle(
        "MemoScoreLabel", parent=body, fontSize=8.5, leading=10, textColor=ink_soft,
    )
    score_value = ParagraphStyle(
        "MemoScoreValue", parent=body, fontName="Helvetica-Bold",
        fontSize=15, leading=17, textColor=purple, alignment=TA_LEFT,
    )

    def p(text: Any, style: ParagraphStyle = body) -> Paragraph:
        return Paragraph(escape(str(text)).replace("\n", "<br/>"), style)

    story = [
        Table([[""]], colWidths=[0.42 * inch], rowHeights=[0.03 * inch],
              style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), purple),
                                ("BOX", (0, 0), (-1, -1), 0, purple)])),
        Spacer(1, 0.12 * inch),
        Paragraph("VIP INVESTMENT MEMO · PILOT", kicker),
        Paragraph("Investment Committee Memo.", title),
    ]
    if memo.get("memo_scores"):
        score_cells = []
        for key, value in memo["memo_scores"].items():
            score = value.get("score", value) if isinstance(value, dict) else value
            score_cells.append([p(_label(key), score_label), p(f"{score} / 10", score_value)])
        columns = 3
        rows = [score_cells[i:i + columns] for i in range(0, len(score_cells), columns)]
        normalized = []
        for row in rows:
            normalized.append(row + [["", ""]] * (columns - len(row)))
        score_table = Table(normalized, colWidths=[2.1 * inch] * columns)
        score_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), paper_soft),
            ("BOX", (0, 0), (-1, -1), 0.5, line),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, line),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        story += [score_table, Spacer(1, 0.08 * inch)]
    for key in MEMO_ORDER:
        value = memo.get(key)
        if value is None:
            continue
        story.append(Paragraph(escape(_label(key)), heading))
        for line_text in _lines(value):
            story.append(p(line_text))
    if memo.get("meta"):
        story.append(Spacer(1, 0.1 * inch))
        story.append(p(f"Generated by {memo['meta'].get('model', '[To be confirmed]')} · pilot",
                       ParagraphStyle("MemoMeta", parent=body, fontSize=8, textColor=ink_dim)))
    doc.build(story)
    return output.getvalue()
