version = 0.1

[production.build.parameters]
cached = true
parallel = true

[production.deploy.parameters]
stack_name = "artpark-eir-api-production"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
fail_on_empty_changeset = false
