// ARTPARK TIR Application — question schema matching the official spec.
// Section 1 (Professional Profile) is handled by the PRE-QUESTION upload step.
// Section 2 Basic Info fields are tagged as cvAutoFill so they show a "parsed" chip.

const SECTIONS = [
  {
    id: "basic",
    index: "01",
    label: "Basic Information",
    blurb: "Most of this was auto-filled from your CV. Take a moment to review.",
    questions: [
      // Contact + background first — these are the fields the resume parser
      // can auto-fill, so the user is mostly confirming values here.
      {
        id: "fullName",
        kind: "short",
        prompt: "What's your full name?",
        help: "As you'd like it to appear on the application.",
        placeholder: "e.g. Dr. Arun Kumar",
        cvAutoFill: true,
        required: true,
      },
      {
        id: "phone",
        kind: "short",
        prompt: "A phone number we can reach you on?",
        help: "We'll use this for interview scheduling only.",
        placeholder: "+91 98765 43210",
        cvAutoFill: true,
        required: true,
      },
      {
        id: "email",
        kind: "email",
        prompt: "And your email?",
        help: "This will be your login anchor and primary channel.",
        placeholder: "you@domain.com",
        cvAutoFill: true,
        required: true,
      },
      {
        id: "org",
        kind: "short",
        prompt: "Where are you right now?",
        help: "Current organization, institution, or 'Independent'. We actively seek outliers from non-tier-1 places.",
        placeholder: "e.g. IISc Bangalore / Independent / Company Name",
        cvAutoFill: true,
        required: true,
      },
      {
        id: "degree",
        kind: "single",
        prompt: "Highest degree achieved?",
        help: "Self-taught engineers with shipped work get equivalent weight — pick whatever's truthful.",
        options: ["Bachelor's Degree", "Master's Degree", "PhD", "Self-taught / Other"],
        cvAutoFill: true,
        required: true,
      },
      {
        id: "incubators",
        kind: "short",
        prompt: "Any other incubators or accelerators — past or present?",
        help: "Write 'None' if not. Note: DST rules prevent companies from drawing DST grants from multiple sources.",
        placeholder: "e.g. None / IIT Madras Incubation Cell",
        required: true,
      },
      {
        id: "hearAbout",
        kind: "single",
        prompt: "How did you hear about ARTPARK?",
        help: "Helps us understand what's working.",
        options: [
          "Referral from friend/colleague",
          "IISc faculty or staff",
          "Social media (LinkedIn, Twitter, etc.)",
          "Event or conference",
          "Search engine",
          "Partner organization",
          "News article or press",
          "Other",
        ],
        required: true,
      },
      // Team questions at the end — once we know who the primary applicant is,
      // ask about co-founders.
      {
        id: "hasTeam",
        kind: "single",
        prompt: "Do you have a team?",
        help: "Solo founders are very welcome. We'll just tailor the rest of the form.",
        options: ["Yes — I have co-founders", "No — going solo for now"],
        required: true,
      },
      {
        id: "teammates",
        kind: "teamInvite",
        prompt: "Invite your co-founders to collaborate on this application.",
        help: "We'll email each person an invite. Everyone shares access to this single application — but only one person can edit at a time. We ask the same three onboarding questions (name, phone, current org) about each teammate.",
        maxMembers: 3,
        required: true,
        conditional: (a) => a.hasTeam === "Yes — I have co-founders",
      },
    ],
  },
  {
    id: "problem",
    index: "02",
    label: "Problem & Importance",
    blurb: "The thing that pulled you in. What won't let you go. Clarity beats jargon — imagine you're telling a brilliant friend from an adjacent technology field.",
    questions: [
      {
        id: "problemDefined",
        kind: "single",
        prompt: "Is the problem you want to solve well-defined?",
        help: "Honest answers help us place you in the right track.",
        options: [
          "Yes, clearly defined",
          "Partially defined",
          "Still exploring the problem space",
        ],
        required: true,
      },
      {
        id: "problemDescribe",
        kind: "long",
        prompt: "Describe the problem. Why is now the right time to solve it?",
        help: "Be as specific as you can. Who feels the pain? How often? What's different about today?",
        placeholder: "Smallholder farmers lack access to real-time soil intelligence, leading to 20–30% yield loss despite increased fertilizer usage…",
        maxChars: 1000,
        minWords: 60,
        required: true,
        conditional: (a) => a.problemDefined && !a.problemDefined.startsWith("Still exploring"),
      },
      {
        id: "problemImportance",
        kind: "long",
        prompt: "Why is this important to solve?",
        help: "Quantify where you can — market size, urgency, human cost, environmental impact.",
        placeholder: "India has 140M+ hectares of farmland. Inefficient input usage leads to ₹1.2L Cr annual losses and environmental degradation…",
        maxChars: 1000,
        minWords: 40,
        required: true,
        conditional: (a) => a.problemDefined && !a.problemDefined.startsWith("Still exploring"),
      },
    ],
  },
  {
    id: "solution",
    index: "03",
    label: "Your Solution",
    blurb: "How you're approaching it, and what makes your angle defensible.",
    questions: [
      {
        id: "stage",
        kind: "single",
        prompt: "How far along are you?",
        help: "No wrong answer — we run tracks for every stage.",
        options: [
          "Still exploring problem area",
          "Literature / research stage",
          "Simulations completed",
          "Lab demos / proof-of-concept",
          "Prototype built",
          "Pilot-ready product",
          "Deployed in real setting with real users",
        ],
        required: true,
      },
      {
        id: "solutionDescribe",
        kind: "long",
        prompt: "Explain your proposed solution and how it connects to the problem.",
        help: "Clarity beats jargon. Imagine you're telling a brilliant friend from an adjacent field.",
        placeholder: "We are building a low-cost IoT soil sensor network with AI-based nutrient prediction…",
        maxChars: 1500,
        minWords: 60,
        required: true,
      },
      {
        id: "coreTech",
        kind: "long",
        prompt: "What's the core technology innovation at the heart of it?",
        help: "The specific laboratory-proven research or cutting-edge advance you intend to translate.",
        placeholder: "Magnetic induction sensor and algorithms that are more accurate because of…",
        maxChars: 1500,
        minWords: 40,
        required: true,
      },
      {
        id: "tenX",
        kind: "long",
        prompt: "How is this a 10× improvement — not an incremental one?",
        help: "Quantify the jump. Incremental gains rarely survive translation; 10× ones can.",
        placeholder: "Reduces sensor cost from ₹15,000 to ₹1,200 while improving accuracy by 3× through adaptive calibration…",
        maxChars: 1500,
        minWords: 40,
        required: true,
      },
      {
        id: "hurdles",
        kind: "long",
        prompt: "What are the primary technical hurdles between lab and real-world deployment?",
        help: "We want to see you've thought about dirt, rain, bad networks, breaking things.",
        placeholder: "Handling soil variability, temperature drift, and sensor degradation over long-term deployment…",
        maxChars: 1500,
        minWords: 40,
        required: true,
      },
      {
        id: "moat",
        kind: "long",
        prompt: "What's your unfair advantage? Why is it difficult to replicate?",
        help: "Dataset, IP, team, distribution, insight — pick the strongest one and make it real.",
        placeholder: "Proprietary dataset from 10,000+ soil samples combined with patented sensor architecture…",
        maxChars: 1500,
        minWords: 40,
        required: true,
      },
      {
        id: "nationalScale",
        kind: "long",
        prompt: "How does this contribute to national transformation — and the path to being globally competitive?",
        help: "Scale thinking. Where does this go over 5–10 years?",
        placeholder: "Starting with India's agri sector, expanding to Southeast Asia and Africa with similar soil conditions…",
        maxChars: 1500,
        minWords: 40,
        required: true,
      },
      {
        id: "customers",
        kind: "long",
        prompt: "Who are your customers, and why will they pay?",
        help: "Economic or operational value proposition. Be concrete about who holds the budget.",
        placeholder: "Farmers save ₹5,000 per acre annually on fertilizer, achieving ROI within one crop cycle…",
        maxChars: 1500,
        minWords: 40,
        required: true,
      },
    ],
  },
  {
    id: "execution",
    index: "04",
    label: "Execution Plan",
    blurb: "How you'll actually get it done.",
    questions: [
      {
        id: "willBreak",
        kind: "long",
        prompt: "What are the top 2–3 things that will break moving from lab to real world?",
        help: "Practical risk awareness. No pretending everything will work.",
        placeholder: "Sensor calibration drift, connectivity issues in rural areas, and physical wear-and-tear…",
        maxChars: 1000,
        minWords: 30,
        required: true,
      },
      {
        id: "milestone",
        kind: "long",
        prompt: "What's the most critical milestone during this residency? What does success look like?",
        help: "One or two sharp outcomes beats a vague roadmap.",
        placeholder: "Deploy 100 pilot units across 3 states with validated performance benchmarks…",
        maxChars: 1000,
        minWords: 30,
        required: true,
      },
      {
        id: "budget",
        kind: "long",
        prompt: "Budget for the year — with justification and milestones.",
        help: "Quarterly milestones tied to line-item spend. You can also upload a PDF/XLS on the Evidence step.",
        placeholder: "Total ₹45L over 12 months. Q1–Q2 (₹20L): hardware R&D…",
        maxChars: 2000,
        minWords: 60,
        required: true,
      },
      {
        id: "failure",
        kind: "long",
        prompt: "Tell us about a time a research direction or prototype failed significantly.",
        help: "How did you pivot? What did it teach you about the path to commercialization? Deep tech rewards delayed gratification — we want to see you've done the time.",
        placeholder: "In 2022, our first sensor architecture couldn't survive monsoon humidity. We…",
        maxChars: 500,
        minWords: 30,
        required: true,
      },
    ],
  },
  {
    id: "evidence",
    index: "05",
    label: "Evidence",
    blurb: "Show, don't just tell.",
    questions: [
      {
        id: "evidenceFiles",
        kind: "files",
        prompt: "Share evidence — publications, patents, prototype photos.",
        help: "Optional, but strong signal. Multiple files OK.",
        accept: ".pdf,.png,.jpg,.jpeg,.doc,.docx",
        multi: true,
        optional: true,
      },
      {
        id: "video",
        kind: "short",
        prompt: "A video of your prototype or product (under 3 minutes).",
        help: "A Loom, YouTube, or Drive link is perfect. Optional but strongly encouraged — photos can be staged, video shows the real thing.",
        placeholder: "https://www.loom.com/share/…",
        optional: true,
      },
      {
        id: "deck",
        kind: "files",
        prompt: "Your 6-slide pitch.",
        help: "Problem → Solution → Core Tech → Customers → Milestones & Budget → Why You. PDF or PPT, max 10MB.",
        accept: ".pdf,.ppt,.pptx",
        required: true,
      },
    ],
  },
  {
    id: "declaration",
    index: "06",
    label: "Declaration",
    blurb: "Last step. Just a few confirmations.",
    questions: [
      {
        id: "declarations",
        kind: "declarations",
        prompt: "A few things to confirm.",
        help: "Tick each to submit.",
        items: [
          { key: "truthful", label: "I confirm the information I've submitted is true and relevant to the questions asked." },
          { key: "refChecks", label: "I consent to reference checks." },
          { key: "terms", label: "I agree to the program terms and data policy." },
          { key: "newsletter", label: "I'd like to receive updates on my application's progress." },
        ],
        required: true,
      },
    ],
  },
];

function flattenQuestions(sections, answers) {
  const out = [];
  sections.forEach((s, si) => {
    s.questions.forEach((q) => {
      if (q.conditional && !q.conditional(answers || {})) return;
      out.push({ section: s, sectionIdx: si, q, globalIdx: out.length });
    });
  });
  return out;
}

export { SECTIONS, flattenQuestions };
