// Theme definitions — 6 aesthetic variations over the same underlying flow.
// Each theme is a set of CSS variables + a label/concept name.

const THEMES = {
  notebook: {
    key: "notebook",
    name: "Research Notebook",
    tag: "rev.01",
    concept: "Off-white paper, plotted grid, rules & tick-marks. Deliberate, methodical.",
    vars: {
      "--bg": "#f4f1ea",
      "--bg-soft": "#ece7dc",
      "--ink": "#1a1a1a",
      "--ink-soft": "#4a4a45",
      "--ink-dim": "#8a867c",
      "--line": "#d7d1c2",
      "--line-strong": "#bab4a3",
      "--accent": "#3213b7",
      "--accent-soft": "#aafcf0",
      "--chip": "#e5e0d2",
      "--gridcell": "36px",
      "--grid-opacity": "0.55",
    },
    bg: "grid",
  },
  terminal: {
    key: "terminal",
    name: "Terminal",
    tag: "tty/0",
    concept: "Dark, mono, blinking cursor energy. For the engineers.",
    vars: {
      "--bg": "#0e0f0d",
      "--bg-soft": "#17181611",
      "--ink": "#e7e5de",
      "--ink-soft": "#b9b6ab",
      "--ink-dim": "#6e6c63",
      "--line": "#2a2b27",
      "--line-strong": "#3e3f39",
      "--accent": "#b8ff5c",
      "--accent-soft": "#2c3a1c",
      "--chip": "#1b1c1a",
      "--gridcell": "32px",
      "--grid-opacity": "0.35",
    },
    bg: "terminal",
  },
  editorial: {
    key: "editorial",
    name: "Editorial Warm",
    tag: "issue nº 01",
    concept: "Warm ivory, generous serifs, like a thoughtful long-form magazine.",
    vars: {
      "--bg": "#f6efe1",
      "--bg-soft": "#ecdfc4",
      "--ink": "#1e1a15",
      "--ink-soft": "#5a5043",
      "--ink-dim": "#948872",
      "--line": "#d6c8a8",
      "--line-strong": "#b8a67f",
      "--accent": "#3213b7",
      "--accent-soft": "#aafcf0",
      "--chip": "#e8dcbe",
      "--gridcell": "40px",
      "--grid-opacity": "0",
    },
    bg: "editorial",
  },
  blueprint: {
    key: "blueprint",
    name: "Blueprint",
    tag: "sheet 01/03",
    concept: "Cool ink on technical-drawing paper. Coordinates, callouts, corner datum.",
    vars: {
      "--bg": "#e7ecef",
      "--bg-soft": "#d5dde2",
      "--ink": "#0a1a2b",
      "--ink-soft": "#3a4b5c",
      "--ink-dim": "#7a8795",
      "--line": "#a8b6c2",
      "--line-strong": "#7a8b9a",
      "--accent": "#3213b7",
      "--accent-soft": "#aafcf0",
      "--chip": "#d1dae1",
      "--gridcell": "24px",
      "--grid-opacity": "0.7",
    },
    bg: "blueprint",
  },
  journal: {
    key: "journal",
    name: "Field Journal",
    tag: "entry 01",
    concept: "Soft cream with annotated margins. Warmest, most personal variation.",
    vars: {
      "--bg": "#fbf7ef",
      "--bg-soft": "#f3ead8",
      "--ink": "#221c14",
      "--ink-soft": "#5e513b",
      "--ink-dim": "#988a6e",
      "--line": "#e0d4ba",
      "--line-strong": "#c3b591",
      "--accent": "#3213b7",
      "--accent-soft": "#aafcf0",
      "--chip": "#ece0c6",
      "--gridcell": "32px",
      "--grid-opacity": "0.25",
    },
    bg: "lines",
  },
  minimal: {
    key: "minimal",
    name: "Minimal Mono",
    tag: "v.0",
    concept: "Near-white, disciplined type, almost nothing else. Swiss-ish.",
    vars: {
      "--bg": "#fafaf7",
      "--bg-soft": "#efefe9",
      "--ink": "#0a0a0a",
      "--ink-soft": "#3a3a3a",
      "--ink-dim": "#9a9a9a",
      "--line": "#e2e2dd",
      "--line-strong": "#c4c4bd",
      "--accent": "#3213b7",
      "--accent-soft": "#aafcf0",
      "--chip": "#efefe9",
      "--gridcell": "48px",
      "--grid-opacity": "0.15",
    },
    bg: "none",
  },
};

const THEME_ORDER = ["notebook", "terminal", "editorial", "blueprint", "journal", "minimal"];

export { THEMES, THEME_ORDER };
