// _juryMock.js — local mock data for jury-mode visual-preview screens.
// Trimmed to 8 entries from the prototype data.js, keeping all jury-related fields.
// This file has NO dependency on window.OS_DATA or any API.

export const STARTUPS = [
  {
    id: 's01', name: 'Karkhana Robotics', founders: ['Aanya Mehta', 'Rohit Kapoor'],
    domain: 'Robotics & Automation', stage: 'Pilot-ready', trl: 5, sub: '12 Apr 2026',
    flag: 'darkgreen', completeness: 92, batch: 'Batch A',
    ai: { overall: 8.4, conf: 92, problem: 8.6, solution: 8.2, tech: 9.0, founders: 7.8, commit: 8.4, integrity: 8.4 },
    rev: { overall: 7.9, problem: 8.0, solution: 7.5, tech: 8.5, founders: 7.5, commit: 8.0, integrity: 8.0, reco: 'yes', notes: 'Strong technical team, deck is tight. Tech score may be a touch high — they over-claim throughput.', disagreements: { tech: 'Reviewer feels the tech throughput claims are slightly exaggerated.' } },
    jury: { potential: 8.5, fit: 8.0, defensibility: 7.5, reco: 'approve' },
    juryAssigned: ['j1', 'j2'],
    flags: ['Throughput claim unverified'], variance: 0.5,
    tags: ['HealthTech adjacent'], chip: 'EVALUATED',
  },
  {
    id: 's02', name: 'Saathi Health AI', founders: ['Dr. Priya Iyer', 'Vikram Shah', 'Neha Bhat'],
    domain: 'Healthcare / MedTech', stage: 'Prototype', trl: 6, sub: '14 Apr 2026',
    flag: 'darkgreen', completeness: 88, batch: 'Batch A',
    ai: { overall: 8.9, conf: 94, problem: 9.2, solution: 8.8, tech: 8.5, founders: 9.0, commit: 9.0, integrity: 8.8 },
    rev: { overall: 8.6, problem: 9.0, solution: 8.5, tech: 8.0, founders: 9.0, commit: 9.0, integrity: 8.0, reco: 'yes', notes: 'Best problem-statement in batch. Team has clinical credibility.' },
    jury: { potential: 9.0, fit: 9.0, defensibility: 8.0, reco: 'approve' },
    juryAssigned: ['j1', 'j3'],
    flags: [], variance: 0.3, chip: 'SHORTLISTED', adminDecision: 'APPROVED',
  },
  {
    id: 's04', name: 'Lumen Surgical', founders: ['Dr. Kabir Joshi', 'Anika Reddy'],
    domain: 'Healthcare / MedTech', stage: 'Lab demo', trl: 7, sub: '09 Apr 2026',
    flag: 'darkgreen', completeness: 95, batch: 'Batch B',
    ai: { overall: 8.1, conf: 90, problem: 8.0, solution: 8.5, tech: 8.8, founders: 7.5, commit: 8.0, integrity: 8.0 },
    rev: { overall: 8.3, problem: 8.5, solution: 8.5, tech: 9.0, founders: 7.5, commit: 8.0, integrity: 8.5, reco: 'yes', notes: 'Regulatory pathway looks plausible. Strong IP.' },
    jury: { potential: 8.0, fit: 8.5, defensibility: 9.0, reco: 'approve' },
    juryAssigned: ['j2', 'j4'],
    interviewDateTime: '2026-04-25T14:00',
    interviewCompleted: true,
    juryInterviewRemarks: '[Kiran Mazumdar-Shaw & Falguni Nayar]: Strong technical foundation. The team demonstrated deep understanding of their market. Recommend acceptance.',
    flags: [], variance: 0.2, chip: 'JURY REVIEW',
  },
  {
    id: 's06', name: 'Anvaya Bio', founders: ['Sneha Krishnan', 'Devansh Gupta'],
    domain: 'Healthcare / MedTech', stage: 'Active pilots', trl: 5, sub: '13 Apr 2026',
    flag: 'darkgreen', completeness: 86, batch: 'Batch B',
    ai: { overall: 7.8, conf: 88, problem: 8.0, solution: 7.5, tech: 8.0, founders: 7.5, commit: 8.0, integrity: 7.5 },
    rev: { overall: 7.2, problem: 7.5, solution: 7.0, tech: 7.5, founders: 7.0, commit: 7.5, integrity: 7.0, reco: 'yes', notes: 'Solid science but slow commercial path.' },
    jury: { potential: 7.5, fit: 7.0, defensibility: 8.5, reco: 'waitlist' },
    juryAssigned: ['j3'],
    flags: ['Long horizon to revenue'], variance: 0.6, chip: 'JURY REVIEW', adminDecision: 'APPROVED',
  },
  {
    id: 's11', name: 'Bandhu AgriCare', founders: ['Pooja Nair', 'Siddharth Iyer'],
    domain: 'Other / Frontier', stage: 'Active pilots', trl: 6, sub: '06 Apr 2026',
    flag: 'darkgreen', completeness: 88, batch: 'Batch D',
    ai: { overall: 8.0, conf: 91, problem: 8.5, solution: 8.0, tech: 7.5, founders: 8.5, commit: 8.0, integrity: 7.5 },
    rev: { overall: 8.0, problem: 8.0, solution: 8.0, tech: 7.5, founders: 8.5, commit: 8.0, integrity: 8.0, reco: 'yes' },
    jury: { potential: 8.5, fit: 8.5, defensibility: 7.0, reco: 'approve' },
    juryAssigned: ['j1', 'j4'],
    flags: [], variance: 0.0, chip: 'ACCEPTED', adminDecision: 'APPROVED',
  },
  {
    id: 's12', name: 'Lithos Materials', founders: ['Aryan Banerjee', 'Ishita Roy'],
    domain: 'Other / Frontier', stage: 'Prototype', trl: 3, sub: '05 Apr 2026',
    flag: 'green', completeness: 68, batch: 'Batch D',
    ai: { overall: 6.0, conf: 74, problem: 6.5, solution: 6.0, tech: 7.0, founders: 5.5, commit: 5.5, integrity: 6.0 },
    rev: { overall: 5.5, problem: 6.0, solution: 5.0, tech: 6.5, founders: 5.5, commit: 5.0, integrity: 5.0, reco: 'no' },
    jury: { potential: 5.5, fit: 5.0, defensibility: 6.0, reco: 'reject' },
    flags: [], variance: 0.5, chip: 'REJECTED', adminDecision: 'REJECTED',
  },
  {
    id: 's15', name: 'Mihira Diagnostics', founders: ['Dr. Tara Pillai', 'Yash Goyal'],
    domain: 'Healthcare / MedTech', stage: 'Active pilots', trl: 7, sub: '01 Apr 2026',
    flag: 'darkgreen', completeness: 96, batch: 'Batch E',
    ai: { overall: 8.7, conf: 93, problem: 9.0, solution: 8.5, tech: 8.5, founders: 9.0, commit: 8.5, integrity: 8.5 },
    rev: { overall: 8.8, problem: 9.0, solution: 8.5, tech: 9.0, founders: 9.0, commit: 8.5, integrity: 8.5, reco: 'yes' },
    jury: { potential: 9.0, fit: 9.0, defensibility: 8.5, reco: 'approve' },
    juryAssigned: ['j2', 'j3'],
    flags: [], variance: 0.1, chip: 'ACCEPTED', adminDecision: 'APPROVED',
  },
  {
    id: 's16', name: 'Nakshatra Drones', founders: ['Aakash Pillai', 'Riya Bose'],
    domain: 'Robotics & Automation', stage: 'Pilot-ready', trl: 5, sub: '02 Apr 2026',
    flag: 'green', completeness: 76, batch: 'Batch E',
    ai: { overall: 7.0, conf: 84, problem: 7.0, solution: 7.5, tech: 7.5, founders: 6.5, commit: 7.0, integrity: 6.5 },
    rev: { overall: 7.2, problem: 7.0, solution: 7.5, tech: 7.5, founders: 7.0, commit: 7.0, integrity: 7.0, reco: 'maybe' },
    jury: { potential: 7.0, fit: 7.5, defensibility: 6.5, reco: 'waitlist' },
    juryAssigned: ['j4'],
    flags: [], variance: 0.2, chip: 'WAITLISTED', adminDecision: 'HOLD',
  },
];

export const JURY = [
  { id: 'j1', name: 'Anand Mahindra', org: 'M&M Group', startups: ['s01', 's02', 's11', 's16'] },
  { id: 'j2', name: 'Kiran Mazumdar-Shaw', org: 'Biocon', startups: ['s01', 's04', 's15'] },
  { id: 'j3', name: 'Nandan Nilekani', org: 'Infosys', startups: ['s02', 's06', 's15'] },
  { id: 'j4', name: 'Falguni Nayar', org: 'Nykaa', startups: ['s04', 's11', 's16'] },
];
